### ISSUE TITLE
0.1.6 fails to build with R 4.6.0: `inspect.cpp: error: 'Rf_findVarInFrame3' was not declared in this scope`

### ISSUE THREAD

**Issue by barracuda156** [hadley/pryr#78]
```
--->  Configuring R-pryr
Executing:  cd "/opt/local/var/macports/build/R-pryr-5454d3ab/work/pryr-0.1.6" && JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home DYLD_LIBRARY_PATH=/opt/local/lib/libgcc:$DYLD_LIBRARY_PATH /opt/local/bin/R CMD build . --no-manual --no-build-vignettes --keep-empty-dirs 
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘pryr’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘pryr_0.1.6.tar.gz’

--->  Building R-pryr
xinstall: mkdir /opt/local/var/macports/build/R-pryr-5454d3ab/work/build
Executing:  cd "/opt/local/var/macports/build/R-pryr-5454d3ab/work/pryr-0.1.6" && JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home DYLD_LIBRARY_PATH=/opt/local/lib/libgcc:$DYLD_LIBRARY_PATH /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/R-pryr-5454d3ab/work/build --install-tests --no-clean-on-error 
* installing *source* package ‘pryr’ ...
** this is package ‘pryr’ version ‘0.1.6’
** using staged installation
** libs
using C++ compiler: ‘g++-mp-16 (MacOS PowerPC gcc16 16.1.0_0+G5+stdlib_flag) 16.1.0’
Warning in system2("xcrun", "--show-sdk-version", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-version 2>&1' had status 64
using SDK: ‘NA’
/opt/local/bin/g++-mp-16 -std=gnu++20 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -flto  -c RcppExports.cpp -o RcppExports.o
/opt/local/bin/g++-mp-16 -std=gnu++20 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -flto  -c bytes.cpp -o bytes.o
/opt/local/bin/g++-mp-16 -std=gnu++20 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -flto  -c inspect.cpp -o inspect.o
inspect.cpp: In function 'bool is_namespace(Rcpp::Environment)':
inspect.cpp:5:10: error: 'Rf_findVarInFrame3' was not declared in this scope
    5 |   return Rf_findVarInFrame3(env, Rf_install(".__NAMESPACE__."), FALSE) != R_UnboundValue;
      |          ^~~~~~~~~~~~~~~~~~
inspect.cpp: In function 'Rcpp::List inspect_rec(SEXP, Rcpp::Environment, std::set<SEXPREC*>&)':
inspect.cpp:23:20: error: 'NAMED' was not declared in this scope
   23 |       _["named"] = NAMED(x),
      |                    ^~~~~
inspect.cpp:84:34: error: 'FRAME' was not declared in this scope
   84 |         _["frame"] = inspect_rec(FRAME(x), base_env, seen),
      |                                  ^~~~~
inspect.cpp:85:35: error: 'ENCLOS' was not declared in this scope
   85 |         _["enclos"] = inspect_rec(ENCLOS(x), base_env, seen),
      |                                   ^~~~~~
inspect.cpp:86:36: error: 'HASHTAB' was not declared in this scope
   86 |         _["hashtab"] = inspect_rec(HASHTAB(x), base_env, seen)
      |                                    ^~~~~~~
inspect.cpp:93:36: error: 'FORMALS' was not declared in this scope
   93 |         _["formals"] = inspect_rec(FORMALS(x), base_env, seen),
      |                                    ^~~~~~~
inspect.cpp:94:33: error: 'BODY' was not declared in this scope
   94 |         _["body"] = inspect_rec(BODY(x), base_env, seen),
      |                                 ^~~~
inspect.cpp:95:33: error: 'CLOENV' was not declared in this scope
   95 |         _["env"]  = inspect_rec(CLOENV(x), base_env, seen)
      |                                 ^~~~~~
inspect.cpp:101:34: error: 'PRVALUE' was not declared in this scope
  101 |         _["value"] = inspect_rec(PRVALUE(x), base_env, seen),
      |                                  ^~~~~~~
inspect.cpp:102:33: error: 'PRCODE' was not declared in this scope
  102 |         _["code"] = inspect_rec(PRCODE(x), base_env, seen),
      |                                 ^~~~~~
inspect.cpp:103:33: error: 'PRENV' was not declared in this scope
  103 |         _["env"]  = inspect_rec(PRENV(x), base_env, seen)
      |                                 ^~~~~
inspect.cpp:109:33: error: 'EXTPTR_PROT' was not declared in this scope
  109 |         _["prot"] = inspect_rec(EXTPTR_PROT(x), base_env, seen),
      |                                 ^~~~~~~~~~~
inspect.cpp:110:32: error: 'EXTPTR_TAG' was not declared in this scope
  110 |         _["tag"] = inspect_rec(EXTPTR_TAG(x), base_env, seen)
      |                                ^~~~~~~~~~
inspect.cpp:129:18: error: 'NAMED' was not declared in this scope
  129 |     _["named"] = NAMED(x),
      |                  ^~~~~
inspect.cpp:133:7: error: 'ATTRIB' was not declared in this scope
  133 |   if (ATTRIB(x) != R_NilValue) {
      |       ^~~~~~
inspect.cpp: In function 'std::string address2(Rcpp::Symbol, Rcpp::Environment)':
inspect.cpp:158:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
  158 |   SEXP object = Rf_findVar(name, env);
      |                 ^~~~~~~~~~
      |                 Rf_findFun
inspect.cpp: In function 'int named2(Rcpp::Symbol, Rcpp::Environment)':
inspect.cpp:166:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
  166 |   SEXP object = Rf_findVar(name, env);
      |                 ^~~~~~~~~~
      |                 Rf_findFun
inspect.cpp:167:10: error: 'NAMED' was not declared in this scope
  167 |   return NAMED(object);
      |          ^~~~~
make: *** [inspect.o] Error 1
ERROR: compilation failed for package ‘pryr’
```

**Comment by barracuda156** [comment]
Also:
```
:info:build promise.cpp: In function 'bool is_promise2(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:6:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build     6 |   SEXP object = Rf_findVar(name, env);
:info:build       |                 ^~~~~~~~~~
:info:build       |                 Rf_findFun
:info:build promise.cpp: In function 'SEXPREC* promise_code(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:13:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build    13 |   SEXP object = Rf_findVar(name, env);
:info:build       |                 ^~~~~~~~~~
:info:build       |                 Rf_findFun
:info:build promise.cpp:14:10: error: 'PRCODE' was not declared in this scope
:info:build    14 |   return PRCODE(object);
:info:build       |          ^~~~~~
:info:build promise.cpp: In function 'SEXPREC* promise_value(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:18:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build    18 |   SEXP object = Rf_findVar(name, env);
:info:build       |                 ^~~~~~~~~~
:info:build       |                 Rf_findFun
:info:build promise.cpp:19:10: error: 'PRVALUE' was not declared in this scope
:info:build    19 |   return PRVALUE(object);
:info:build       |          ^~~~~~~
:info:build promise.cpp: In function 'bool promise_evaled(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:23:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build    23 |   SEXP object = Rf_findVar(name, env);
:info:build       |                 ^~~~~~~~~~
:info:build       |                 Rf_findFun
:info:build promise.cpp:24:10: error: 'PRVALUE' was not declared in this scope
:info:build    24 |   return PRVALUE(object) != R_UnboundValue;
:info:build       |          ^~~~~~~
:info:build promise.cpp: In function 'SEXPREC* promise_env(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:28:17: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build    28 |   SEXP object = Rf_findVar(name, env);
:info:build       |                 ^~~~~~~~~~
:info:build       |                 Rf_findFun
:info:build promise.cpp:29:10: error: 'PRENV' was not declared in this scope
:info:build    29 |   return PRENV(object);
:info:build       |          ^~~~~
:info:build promise.cpp: In function 'Rcpp::RObject makeExplicit(SEXP)':
:info:build promise.cpp:41:17: error: 'PRCODE' was not declared in this scope
:info:build    41 |     SEXP code = PRCODE(prom);
:info:build       |                 ^~~~~~
:info:build In file included from /opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:72,
:info:build                  from /opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include/RcppCommon.h:30,
:info:build                  from /opt/local/Library/Frameworks/R.framework/Versions/4.6/Resources/library/Rcpp/include/Rcpp.h:27,
:info:build                  from promise.cpp:1:
:info:build promise.cpp:46:32: error: 'PRCODE' was not declared in this scope
:info:build    46 |   SEXP args = PROTECT(Rf_lcons(PRCODE(prom), R_NilValue));
:info:build       |                                ^~~~~~
:info:build /opt/local/Library/Frameworks/R.framework/Resources/include/Rinternals.h:357:36: note: in definition of macro 'PROTECT'
:info:build   357 | #define PROTECT(s)      Rf_protect(s)
:info:build       |                                    ^
:info:build promise.cpp:50:34: error: 'PRENV' was not declared in this scope
:info:build    50 |   formula.attr(".Environment") = PRENV(prom);
:info:build       |                                  ^~~~~
:info:build promise.cpp: In function 'Rcpp::RObject explicitPromise(Rcpp::Symbol, Rcpp::Environment)':
:info:build promise.cpp:58:15: error: 'Rf_findVar' was not declared in this scope; did you mean 'Rf_findFun'?
:info:build    58 |   SEXP prom = Rf_findVar(name, env);
:info:build       |               ^~~~~~~~~~
:info:build       |               Rf_findFun
:info:build make: *** [promise.o] Error 1
```
